### ISSUE TITLE
Bad User Request Exception

### ISSUE THREAD

**Issue by falko** [camunda-consulting/on-demand-call-activity#49]
As part of #28 we encountered Bad User Request Exception in case of Call Activity performing just a service call asynchronously because the execution that should receive a signal was not committed when the signal was sent.

- Retries used as a workaround
- But the situation should be prevented, either by waiting longer or committing the TX faster
- Waiting longer is not an option because up to 30s process instance duration is required
- On committing the TX faster:
  - Logfiles showed no activity in Camunda code that explains the delay
    - except the lookup of the process definition with key=null (this is now fixed in #50)
  - Profiling with VisualVM showed initially a high latency to PostgreSQL server
    - But it also happened in NFT where there is minimal latency (2-10ms)

Next Steps:
- [x] setup PostgreSQL locally
- [x] profile again with VisualVM

**Comment by falko** [comment]
The observed exception has changed due to PR #18 being merged.
Profiling with VisualVM and sampling rate 100ms did not show any anomalies.
Next step: profiling with 20ms

**Comment by falko** [comment]
Next step: Prajakta runs profiler with 20ms sampling rate and sends result to Falko for review.

**Comment by sawantp02** [comment]
[SendSignalErrorRetry.zip](https://github.com/camunda-consulting/on-demand-call-activity/files/5781164/SendSignalErrorRetry.zip)

**Comment by OHUser** [comment]
[SendSignalErrorRetry.zip](https://github.com/camunda-consulting/on-demand-call-activity/files/5781177/SendSignalErrorRetry.zip)

**Comment by falko** [comment]
Next Steps: Prajakta to send logs+profiler snapshot to Falko for review.

**Comment by OHUser** [comment]
[BadUserRequestException_SamplingRate20ms.zip](https://github.com/camunda-consulting/on-demand-call-activity/files/5783310/BadUserRequestException_SamplingRate20ms.zip)

**Comment by falko** [comment]
Next Steps: Falko to review and maybe involve engineering

**Comment by falko** [comment]
One go-live in March which will likely not use this plugin but others are coming up.

**Comment by falko** [comment]
Analysis of the last test:
09.712 [main] INFO  o.c.b.e.b.c.o.p.ChildProcessProvider - ChildProcessProvider execute : 1
between these two log lines the asynchronous lambda is scheduled to execute with a 250ms delay
09.800 [main] INFO  o.c.b.e.b.c.o.p.ChildProcessProvider - ChildProcessProvider execute finished: 1
09.800 [main] DEBUG org.camunda.bpm.engine.cmd - ENGINE-13011 closing existing command context
09.816 [main] DEBUG org.camunda.bpm.engine.persistence - ENGINE-03006 Cache state after flush: [
engine is preparing commit
09.932 [ForkJoinPool.commonPool-worker-1] INFO  o.c.b.e.b.c.o.p.ChildProcessProvider - ChildProcessProvider try : 23
delayed execution started ALREADY after 220ms
10.060 [main] DEBUG org.camunda.bpm.engine.tx - ENGINE-11002 firing event committed...
10.060 [main] DEBUG o.a.i.d.pooled.PooledDataSource - Returned connection 1463835093 to pool.
engine commit after 260 ms

This test rather looks like the `delayedExecutor` scheduled the lambda execution a little early. The TX commit was within expected time. So basically this test run didn't reproduce the problem.

Next: rerun test with same setup, same logging and same profile resolution. Try to find a run where the TX commit take much longer than 250 ms.

**Comment by OHUser** [comment]
[Exception_delay250.zip](https://github.com/camunda-consulting/on-demand-call-activity/files/6043099/Exception_delay250.zip)

PFA Zip File- Profiler Configuration having frequency 20
Log level -trace
delay -250ms

**Comment by falko** [comment]
Analysis of the last test:
07.112 [main] INFO  o.c.b.e.b.c.o.p.ChildProcessProvider - ChildProcessProvider execute finished: 1
07.362 [ForkJoinPool.commonPool-worker-1] INFO  o.c.b.e.b.c.o.p.ChildProcessProvider - ChildProcessProvider try : 24
08.321 [main] DEBUG o.c.b.e.i.p.e.V.insertVariableInstance - ==> Parameters: 827(String), boolean(String), OnDemandCallActivity_ASYNC_SERVICE_CALL_On-demand_Call_Activity(String), engine-plugin-on-demand-call-activity:9:803(String), 817(String), 825(String), null, null, null, null, null, null, 1(Long), null, null, 825(String), 1(Long), true(Boolean), null
engine is done with SQL preparation
1.6 seconds later...
09.922 [main] DEBUG org.camunda.bpm.engine.tx - ENGINE-11002 firing event committing...

Next step: Chaitali to provide a CSV export of the profiling results

**Comment by OHUser** [comment]
PFA CSV export for profiler with Java logs
[Exception_delay250.zip](https://github.com/camunda-consulting/on-demand-call-activity/files/6084940/Exception_delay250.zip)

**Comment by falko** [comment]
Analysis:
13.371 [main] DEBUG org.camunda.bpm.engine.cmd - ENGINE-13005 Starting command -------------------- StartProcessInstanceCmd ----------------------
17.077 [main] INFO  o.c.b.e.b.c.o.p.ChildProcessProvider - ChildProcessProvider execute finished: 1
17.331 [ForkJoinPool.commonPool-worker-1] INFO  o.c.b.e.b.c.o.p.ChildProcessProvider - ChildProcessProvider try : 24
18.310 [main] DEBUG o.c.b.e.i.p.e.V.insertVariableInstance - ==> Parameters: 127(String), boolean(String), OnDemandCallActivity_ASYNC_SERVICE_CALL_On-demand_Call_Activity(String), engine-plugin-on-demand-call-activity:2:103(String), 117(String), 125(String), null, null, null, null, null, null, 1(Long), null, null, 125(String), 1(Long), true(Boolean), null
engine is done with SQL preparation
1.6 seconds later...
19.946 [main] DEBUG org.camunda.bpm.engine.tx - ENGINE-11002 firing event committing...

**Comment by falko** [comment]
Idea: Use TX listener for thread synchronization

**Comment by falko** [comment]
@OHUser could you please test the experimental fix I commit in 92cba86 against your local PostgreSQL database? If this fixes the issue, I will build a proper version that doesn't block the thread and can also handle transaction rollbacks.

**Comment by OHUser** [comment]
Hi, I have tested the fix. and its working fine. I did not get any exception after these changes

**Comment by falko** [comment]
Falko to replace the experimental fix with a cleaner version, i.e. without blocking a thead.

**Comment by falko** [comment]
@OHUser Hi Chaitali, could you please review the latest changes in the `ohuser` branch and test it against PostgreSQL? If you don't see any new issues, you can merge the PR into master.

**Comment by falko** [comment]
There is no more sleeping – neither in the tests nor in the test implementations of MultiThreadedJavaDelegate or ChildProcessProvider. I also removed some race conditions from the tests.

**Comment by falko** [comment]
Notes from today's meeting: Tests have been rerun on PostgreSQL with no issues.

**Comment by falko** [comment]
@OHUser Hi Chaitali, could you please review the latest changes in the `ohuser` branch and test it against PostgreSQL? After that, please merge PR #28 into master, unless there are errors.

**Comment by OHUser** [comment]
@falko  I tried to build orchestartor code using new Code. Build is failing in testcases with NullPointer Exception. PFB image and logs.

"C:\Program Files\Java\jdk-11.0.9\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:4749,suspend=y,server=n -ea -Dcom.amdocs.msnext.root.level.appender.ref=console --illegal-access=permit -Didea.test.cyclic.buffer.size=4194304 -javaagent:C:\Users\patilcha\.IdeaIC2019.3\system\groovyHotSwap\gragent.jar -javaagent:C:\Users\patilcha\.IdeaIC2019.3\system\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4\lib\idea_rt.jar" com.intellij.rt.execution.CommandLineWrapper C:\Users\patilcha\AppData\Local\Temp\idea_classpath1497901123 com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit4 com.amdocs.digital.orderworkflow.orchestrator.pa.async.callactivity.FlowContextUpdatorChildProcessProviderTest,execute_asyncCall_success
Connected to the target VM, address: '127.0.0.1:4749', transport: 'socket'
21:40:03.034 [main] INFO  c.a.d.o.o.p.a.c.FlowContextUpdatorChildProcessProvider - Running childProcessProvider...
21:40:03.927 [main] DEBUG c.a.d.o.o.p.a.c.FlowContextUpdatorChildProcessProvider - Executing the FlowContext update flow in async thread, return null

java.lang.NullPointerException
	at org.camunda.bpm.extension.bpmn.servicetask.asynchronous.ThreadSaveExecution.<init>(ThreadSaveExecution.java:58)
	at org.camunda.bpm.extension.bpmn.callactivity.ondemand.plugin.OnDemandCallActivityExecution.<init>(OnDemandCallActivityExecution.java:27)
	at org.camunda.bpm.extension.bpmn.callactivity.ondemand.plugin.AbstractChildProcessProvider.getChildProcessDefinitionKey(AbstractChildProcessProvider.java:53)
	at com.amdocs.digital.orderworkflow.orchestrator.pa.async.callactivity.FlowContextUpdatorChildProcessProviderTest.execute_asyncCall_success(FlowContextUpdatorChildProcessProviderTest.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:46)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
 
![image](https://user-images.githubusercontent.com/67940132/118154093-47c00e00-b434-11eb-90c3-cfbdbffd0dd6.png)

**Comment by falko** [comment]
It sounds like your `FlowContextUpdatorChildProcessProviderTest` leads to a situation where there is no `CommandContext`. The stack trace looks like you are testing the child process provider outside of the engine without a running process instance and therefore there is no `CommandConext` available. I see multiple options:
1. You could have a look at engine test suite if there is some kind of mock for the `CommandContext` for situations like this or create a mock object yourself.
2. You could redesign the `ThreadSafeExecution` for better testability, e.g. add a constructor that allows to pass in a mock of `CommandContext`.
3. Test inside the engine with a running process instance.

**Comment by aaronlaye** [comment]
Hi @OHUser , do you have any updates on this issue?

Thanks,
Aaron

**Comment by OHUser** [comment]
@falko I have made changes suggested by you and it worked. Merging changes to master.
