### ISSUE TITLE
Engine Test Suite: TelemetryReporterTest fails with java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by falko** [camunda-consulting/on-demand-call-activity#63]
```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.108 s <<< FAILURE! - in org.camunda.bpm.engine.test.api.mgmt.telemetry.TelemetryReporterTest
Error:  org.camunda.bpm.engine.test.api.mgmt.telemetry.TelemetryReporterTest  Time elapsed: 2.108 s  <<< ERROR!
com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.net.BindException: Address already in use (Bind failed)
	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:192)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:58)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use (Bind failed)
	at com.github.tomakehurst.wiremock.jetty6.Jetty6HttpServer.start(Jetty6HttpServer.java:101)
	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:190)
	... 11 more
Caused by: java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:392)
	at java.net.ServerSocket.<init>(ServerSocket.java:254)
	at org.mortbay.jetty.bio.SocketConnector.newServerSocket(SocketConnector.java:80)
	at org.mortbay.jetty.bio.SocketConnector.open(SocketConnector.java:73)
	at org.mortbay.jetty.AbstractConnector.doStart(AbstractConnector.java:283)
	at org.mortbay.jetty.bio.SocketConnector.doStart(SocketConnector.java:147)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.Server.doStart(Server.java:235)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.github.tomakehurst.wiremock.jetty6.Jetty6HttpServer.start(Jetty6HttpServer.java:99)
	... 12 more
```

**Comment by falko** [comment]
done.
